println("Welcome to maximus multiplicatus where all your numbers will magically be multiplied")
print("enter your first number: ")
number1 = (parse(Int64, readline()))
print("second number: ")
number2= (parse(Float64, readline()))
println("And the magically number you wished for is $(number1 * number2)")
